### PR TITLE
Added Android Dev Bootcamp

### PR DESCRIPTION
**Pull request by bhaveshgoyal182**
Added Android O & Java - The Complete Android Development Bootcamp a beginner friendly course.

### CODE REVIEW

**Review by androiddevnotes — CHANGES_REQUESTED** [review]
Thank you for the Pull Request!

But this repo is primarily focused on Kotlin courses. I make few exceptions for JAVA but those have to be very well done. There are better alternatives in Kotlin for the course you linked.

Please submit resources in Kotlin that could be helpful and create another commit : )

Please join the Discord server where we discuss open-source, android dev, and content creation. Invite link - https://discord.gg/vBnEhuC

**Comment by bhaveshgoyal182** [comment]
Changes Done Please Have A Look!

**Review by androiddevnotes — APPROVED** [review]
Thank you for the Pull Request!

Please join the Discord server where we discuss open-source, android dev, and content creation. Invite link - https://discord.gg/vBnEhuC

**Comment by bhaveshgoyal182** [comment]
@androiddevnotes If you liked the course then please label this PR with hacktoberfest-accepted as it would be helpful for me.

**Comment by androiddevnotes** [comment]
@bhaveshgoyal182 done : )

**Comment by bhaveshgoyal182** [comment]
Thanks a Lot @androiddevnotes :)

**Pull request merged**
